App\Entity\eleve:

    type: entity

    id:
        id:
            type: integer
            generator :
                strategy : AUTO

    fields:
        nom:
            type : string
            length: 155

        prenom:
            type: string
            length: 155

        mail:
            type: string
            length: 155

        promo:
            type: integer


    ManyToone:
        option2:
            targetEntity: App\Entity\Option
            inversedBy: eleve2
            joinColumn:
                name: option2_id
                referencedColumnName: id
                nullable: true

        option3:
            targetEntity: App\Entity\Option
            inversedBy: eleve3
            joinColumn:
                name: option3_id
                referencedColumnName: id
                nullable: true

        pdprofil:
            targetEntity: App\Entity\pdprofil
            joinColumn:
                name: pdprofil_id
                referencedColumnName: id
                nullable: true

