App\Entity\pdprofil:

    type: entity

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:

        nom:
            type: string
            length: 155
            nullable: true

        lien:
            type: string
            length: 255

        alt:
            type: text
            nullable: true


    lifecycleCallbacks:
        prePersist: [ setCreatedAt ]